# -*- coding: utf-8 -*-
"""Healthcare Analytics for Doctor Visits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7iwawsppdrvCQJdpBbd4HLKUlxoWrnt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("/content/1776250375-P2-Healthcare Analytics for Doctor Visits.csv")

#top 5  rows
df.head()

# last 5 rows
df.tail()

df.shape

df.info()

#stastical information of the dataset
df.describe()

#Checking the null values
df.isnull().sum()

"""### Univariate Analysis

Let's start by visualizing the distribution of some key numerical features like `age`, `income`, and `visits` using histograms. Then, we will look at the distribution of categorical features, starting with `gender`.
"""

# Plotting histograms for numerical features
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

sns.histplot(df['age'], kde=True, ax=axes[0], color='skyblue')
axes[0].set_title('Distribution of Age')
axes[0].set_xlabel('Age')
axes[0].set_ylabel('Frequency')

sns.histplot(df['income'], kde=True, ax=axes[1], color='lightcoral')
axes[1].set_title('Distribution of Income')
axes[1].set_xlabel('Income')
axes[1].set_ylabel('Frequency')

sns.histplot(df['visits'], kde=True, ax=axes[2], color='lightgreen')
axes[2].set_title('Distribution of Visits')
axes[2].set_xlabel('Number of Visits')
axes[2].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

# Plotting a bar plot for the 'gender' categorical feature
plt.figure(figsize=(8, 6))
sns.countplot(x='gender', data=df, palette='viridis', hue='gender', legend=False)
plt.title('Distribution of Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()



"""### Gender Analysis: Counts

Let's get the precise counts for each gender category in the dataset.
"""

# Get the count of each gender
gender_counts = df['gender'].value_counts()
display(gender_counts)

gender_analysis = (
    df.groupby("gender")["visits"]
      .agg(["count", "mean", "median"])
      .reset_index()
)

display(gender_analysis)

sns.barplot(
    data=gender_analysis,
    x="gender",
    y="mean",
    color="teal"
)

plt.title("Average Doctor Visits by Gender")
plt.xlabel("Gender")
plt.ylabel("Mean recorded visits")
plt.show()

illness_analysis = (
    df.groupby("illness")["visits"]
        .agg(["count", "mean"])
        .reset_index()
)

display(illness_analysis)

sns.lineplot(
    data=illness_analysis,
    x="illness",
    y="mean",
    marker="o"
)

plt.title("Illness Score vs. Average Doctor Visits")
plt.xlabel("Illness score")
plt.ylabel("Mean recorded visits")
plt.show()

"""### Additional Univariate Analysis

Let's continue with more univariate plots to understand the distribution of `health`, `reduced`, and `private`.
"""

# Plotting histograms for 'health' and 'reduced'
fig, axes = plt.subplots(1, 2, figsize=(15, 6))

sns.histplot(df['health'], kde=True, ax=axes[0], color='cornflowerblue')
axes[0].set_title('Distribution of Health Status')
axes[0].set_xlabel('Health Status (0-12)')
axes[0].set_ylabel('Frequency')

sns.histplot(df['reduced'], kde=True, ax=axes[1], color='mediumpurple')
axes[1].set_title('Distribution of Reduced Activity Days')
axes[1].set_xlabel('Reduced Activity Days')
axes[1].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

# Plotting a count plot for 'private' insurance
plt.figure(figsize=(7, 6))
sns.countplot(x='private', data=df, palette='Dark2', hue='private', legend=False)
plt.title('Distribution of Private Health Insurance')
plt.xlabel('Private Insurance (yes/no)')
plt.ylabel('Count')
plt.show()

"""### Multivariate Analysis

Let's explore the relationships between different variables using multivariate plots.
"""

# Scatter plot of Age vs. Visits
plt.figure(figsize=(10, 6))
sns.scatterplot(x='age', y='visits', data=df, alpha=0.6, color='darkblue')
plt.title('Age vs. Number of Doctor Visits')
plt.xlabel('Age')
plt.ylabel('Number of Visits')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

# Scatter plot of Income vs. Visits
plt.figure(figsize=(10, 6))
sns.scatterplot(x='income', y='visits', data=df, alpha=0.6, color='darkgreen')
plt.title('Income vs. Number of Doctor Visits')
plt.xlabel('Income')
plt.ylabel('Number of Visits')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

# Box plot of Income by Gender
plt.figure(figsize=(10, 6))
sns.boxplot(x='gender', y='income', data=df, palette='pastel', hue='gender', legend=False)
plt.title('Income Distribution by Gender')
plt.xlabel('Gender')
plt.ylabel('Income')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Box plot of Visits by Health Status
plt.figure(figsize=(12, 6))
sns.boxplot(x='health', y='visits', data=df, palette='viridis', hue='health', legend=False)
plt.title('Number of Doctor Visits by Health Status')
plt.xlabel('Health Status (0 = best, 12 = worst)')
plt.ylabel('Number of Visits')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Box plot of Visits by Private Insurance
plt.figure(figsize=(8, 6))
sns.boxplot(x='private', y='visits', data=df, palette='mako', hue='private', legend=False)
plt.title('Number of Doctor Visits by Private Insurance')
plt.xlabel('Private Insurance')
plt.ylabel('Number of Visits')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()